# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180829_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author', verbose_name='作者'),
        ),
    ]
